Use real SSL certificate for Guacamole
cisagov/pca-terraform pull request #2
Opened 2019-08-28 15:30 UTC by dav3r

This PR enables Guacamole to pull a proper SSL certificate from the specified S3 bucket.  It also opens up some additional ingress/egress ports that are needed for boto3 to talk to the S3 bucket.  Finally, it sets up a public DNS record for the Guacamole EC2 instance so that it will match the name on the certificate.

2019-08-28 17:04 UTC, felddy approved these changes
Nice.  A very special PR for a very special man.

2019-08-28 18:04 UTC, jsf9k approved these changes
This looks great @dav3r.

2019-08-28 18:10 UTC, KyleEvers requested changes

2019-08-28 18:10 UTC, KyleEvers commented on install-certificates.tpl.yml
> +      This file is a template.  It should be processed by terraform.
Can you add a comment with a reference to https://github.com/cisagov/certboto-docker for reference on how you are generating the certificates installed by this script. If not here specifically, wherever you see fit.

2019-08-28 18:43 UTC, dav3r commented on install-certificates.tpl.yml
> +      This file is a template.  It should be processed by terraform.
I need to update the README for this project- that is something that I can put in there.

2019-08-28 19:02 UTC, KyleEvers commented on install-certificates.tpl.yml
> +      This file is a template.  It should be processed by terraform.
Sounds good to me 👍

2019-08-28 19:02 UTC, KyleEvers approved these changes

2019-08-29 19:49 UTC, dav3r commented on install-certificates.tpl.yml
> +      This file is a template.  It should be processed by terraform.
@KyleEvers - Updated the README in https://github.com/cisagov/pca-terraform/pull/2/commits/fefaf3522cea9843a6eb49394a13f9daf726daec

2019-08-29 19:52 UTC, merged